using MessageBridge.IntegrationTests.Fixtures;
using Npgsql;
using Shouldly;
using Xunit;

namespace MessageBridge.IntegrationTests.Persistence;

[Trait("Category", "Integration")]
[Collection(IntegrationTestCollection.Name)]
public sealed class DatabaseIdentityBootstrapTests(IntegrationEnvironmentFixture fixture)
{
    private readonly IntegrationEnvironmentFixture _fixture = fixture;

    [Fact]
    public async Task RuntimeRole_HasDml_AndCannotCreateTables()
    {
        await using var scenario = await IdentityBootstrapScenario.CreateMigratedAsync(_fixture);
        await scenario.ApplyAsync();

        await using var runtimeConnection = await scenario.OpenRuntimeConnectionAsync();
        await ExecuteAsync(
            runtimeConnection,
            """
            INSERT INTO message_processing_history
                (id, message_id, message_type, status, payload_hash, provider,
                 provider_metadata, attempt_count, created_at, updated_at)
            VALUES
                (gen_random_uuid(), 'bootstrap-contract', 'test', 'Pending', 'hash',
                 'test', '{}'::jsonb, 0, now(), now());
            UPDATE message_processing_history
            SET status = 'Completed'
            WHERE message_id = 'bootstrap-contract';
            SELECT count(*) FROM message_processing_history
            WHERE message_id = 'bootstrap-contract';
            DELETE FROM message_processing_history
            WHERE message_id = 'bootstrap-contract';
            """);

        var exception = await Should.ThrowAsync<PostgresException>(() =>
            ExecuteAsync(runtimeConnection, "CREATE TABLE runtime_forbidden(id integer);"));
        exception.SqlState.ShouldBe(PostgresErrorCodes.InsufficientPrivilege);

        exception = await Should.ThrowAsync<PostgresException>(() =>
            ExecuteAsync(runtimeConnection, "CREATE TEMP TABLE runtime_temp_forbidden(id integer);"));
        exception.SqlState.ShouldBe(PostgresErrorCodes.InsufficientPrivilege);
    }

    [Fact]
    public async Task MigratorRole_HasDdl_AndDefaultPrivilegesFlowToRuntime()
    {
        await using var scenario = await IdentityBootstrapScenario.CreateMigratedAsync(_fixture);
        await scenario.ApplyAsync();

        await using var migratorConnection = await scenario.OpenMigratorConnectionAsync();
        await ExecuteAsync(
            migratorConnection,
            """
            CREATE TABLE migrator_contract(
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                value text NOT NULL);
            ALTER TABLE migrator_contract ADD COLUMN updated boolean NOT NULL DEFAULT false;
            """);

        await using var runtimeConnection = await scenario.OpenRuntimeConnectionAsync();
        await ExecuteAsync(
            runtimeConnection,
            """
            INSERT INTO migrator_contract(value) VALUES ('created by runtime');
            UPDATE migrator_contract SET updated = true;
            DELETE FROM migrator_contract WHERE updated;
            """);

        await ExecuteAsync(migratorConnection, "DROP TABLE migrator_contract;");
    }

    [Fact]
    public async Task CrossDatabaseDenied_Idempotent_And_VerifyMode()
    {
        await using var scenario = await IdentityBootstrapScenario.CreateMigratedAsync(_fixture);
        var production = await scenario.CreateEmptyTargetAsync();

        await Should.ThrowAsync<PostgresException>(() => scenario.VerifyAsync(production));
        await scenario.ApplyAsync();
        var runtimeIdentifier = await scenario.GetRoleIdentifierAsync(
            scenario.Development.RuntimeRole);
        var migratorIdentifier = await scenario.GetRoleIdentifierAsync(
            scenario.Development.MigratorRole);
        await scenario.ApplyAsync();
        (await scenario.GetRoleIdentifierAsync(scenario.Development.RuntimeRole))
            .ShouldBe(runtimeIdentifier);
        (await scenario.GetRoleIdentifierAsync(scenario.Development.MigratorRole))
            .ShouldBe(migratorIdentifier);
        await scenario.ApplyAsync(production);
        await scenario.VerifyAsync(scenario.Development);
        await scenario.VerifyAsync(production);

        await using var productionRuntime = await scenario.OpenRuntimeConnectionAsync(production);
        productionRuntime.State.ShouldBe(System.Data.ConnectionState.Open);

        var exception = await Should.ThrowAsync<PostgresException>(() =>
            scenario.OpenDevelopmentRuntimeConnectionToAsync(production));
        exception.SqlState.ShouldBe(PostgresErrorCodes.InsufficientPrivilege);

        exception = await Should.ThrowAsync<PostgresException>(() =>
            scenario.OpenDevelopmentMigratorConnectionToAsync(production));
        exception.SqlState.ShouldBe(PostgresErrorCodes.InsufficientPrivilege);

        exception = await Should.ThrowAsync<PostgresException>(() =>
            scenario.OpenProductionRuntimeConnectionToAsync(production, scenario.Development));
        exception.SqlState.ShouldBe(PostgresErrorCodes.InsufficientPrivilege);

        exception = await Should.ThrowAsync<PostgresException>(() =>
            scenario.OpenProductionMigratorConnectionToAsync(production, scenario.Development));
        exception.SqlState.ShouldBe(PostgresErrorCodes.InsufficientPrivilege);
    }

    private static async Task ExecuteAsync(NpgsqlConnection connection, string sql)
    {
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync();
    }
}
